### ISSUE TITLE
请教您一个问题

### ISSUE THREAD

**Issue by bearcai** [lz-wang/obsidian-image-uploader#3]
我看到你有用File Run和obsidian，好像可以用Remotely Save插件同步，有试过吗？

**Comment by lz-wang** [comment]
抱歉，没用过Remotely Save插件，我一直用的腾讯云的COS做图片附件同步

**Comment by bearcai** [comment]
> 抱歉，没用过Remotely Save插件，我一直用的腾讯云的COS做图片附件同步

感谢恢复！
